theme: minima
title: Docker
author: Yulin Zhao
description: This blog will go through a comprehensive learning journey of Docker, starting from understanding what containers are, creating and managing containers, to exploring various details of container techniology (networking/storage/service orchestration/monitoring), and then advancing to mastering container technology through continuous integration and continuous deployment (CI/CD) using containers.
